= Dew-Framework

*基于Spring Cloud的服务封装*

=== 设计理念
对Spring Cloud做一层薄的封装，力求提供一个完备的生产级微服务架构，最小化的学习成本，快速上手，在不改变Spring Cloud的开发模式下做简洁明了的扩展。


=== 模块与功能

IMPORTANT: 当前先迁移 `modules` 和 三个核心的 `config` `register` `Gateway`服务。

==== *com.tairanchina.csp.dew:parent* Dew 父工程

. 提供了Spring Boot & Spring Cloud 的基础pom结构
. 通过 `maven clean package -P package`来生成fatjar

==== *com.tairanchina.csp.dew:boot-core* Dew Spring Boot 封装

. `Dew.cluster.*` - 常用分布式服务（Cache、Lock、Map、MQ）
. `entity`包 - 常用实体模型
. `controller & service`包 - 服务脚手架（CRUDS，针对实体的创建、查询、更新、删除、启用禁用）
. `DewRepository<E extends IdEntity>` - 基于Spring Data JPA的常用方式扩展
. `Resp<E>` - 统一返回信息格式
. `DewLogger` - 可跟踪日志支持（请求级ID）
. `Dew.EB.*` 统一生产、测试环境的微服务路由
. Swagger文档

[source,xml]
.可选功能
----
<!-- 启用对应的分布式服务支持 -->
 <dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>cluster-spi-redis</artifactId>
    <version>${dew.version}</version>
</dependency>
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>cluster-spi-hazelcast</artifactId>
    <version>${dew.version}</version>
</dependency>
<dependency>
    <groupId>com.tairanchina.csp.dew</groupId>
    <artifactId>cluster-spi-ignite</artifactId>
    <version>${dew.version}</version>
</dependency>
<!-- 启用web支持 -->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
<!-- 启用关系型数据支持（如MySQL） -->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.41</version>
</dependency>
<!-- 启用Swagger日志 -->
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>2.6.1</version>
</dependency>
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.6.1</version>
</dependency>
----

==== *com.tairanchina.csp.dew:cloud-core* Dew Spring Cloud 封装

. 引入Spring Cloud常用依赖

==== *com.tairanchina.csp.dew:config* 配置中心服务

. 集成Spring Config和Spring Security

==== *com.tairanchina.csp.dew:registry* 注册中心服务

. 集成Eureka Server和Spring Security

==== *com.tairanchina.csp.dew:gateway* 网关服务

. 集成Zuul网关
. 与Auth配合，支持权限认证（暂不迁移）

==== *com.tairanchina.csp.dew:gateway* Websocket网关服务

. 支持Websocket的网关

==== *com.tairanchina.csp.dew:auth* 多租户的RBAC权限服务

==== *com.tairanchina.csp.dew:logger* 日志服务

. 集成Zipkin

==== *com.tairanchina.csp.dew:monitor* 集群监控服务

. 集成Turbine和Hystrix Dashboard

=== 运行环境

Java8以上、可选：Redis、Hazcelcast、Ignite、RabbitMQ、关系型数据库（默认MySQL）
